version: '3.1'

services:

  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <pass>
    volumes:
      - <volume>:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres
